name: tree_manager
description: Tree Manager application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.17
  flutter_svg: ^2.0.5
  http: ^1.2.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  #catcher: ^0.2.7
  #progress_dialog: ^1.2.0
  #getflutter: ^1.0.0-dev.1
  #auto_size_text: ^2.1.0
  flutter_date_pickers: ^0.4.3
  flutter_image_compress: ^2.3.0
  flutter_material_color_picker: ^1.1.0+2
  permission_handler: ^11.3.1
#  multi_image_picker: ^4.8.0+1
  image_picker: ^1.1.2
#  image_picker: ^0.7.4
#  image_picker: ^0.8.7+3
  multiple_images_picker: ^1.0.1
  #flutter_flexible_toast: ^0.1.3
  intl: ^0.19.0
  double_back_to_close_app: ^2.1.0
  # flutter_phone_state: ^0.5.9
  #call_number: ^0.0.1
  share_plus: ^7.2.2
  path_provider: ^2.0.0
  #pinch_zoom_image_updated: ^0.2.6
#  cached_network_image: ^3.2.0
  cached_network_image: ^3.4.0
  maps_launcher: ^2.2.1
  flutter_signature_pad: ^3.0.1
  steps_indicator: ^1.3.0
#  velocity_x: ^4.1.0
  toast: ^0.3.0
  store_redirect: ^2.0.2
  #get_version: ^0.2.2
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
#  package_info: ^2.0.0
  image: ^4.2.0
  # save_in_gallery: ^0.1.3
  background_locator: ^1.6.12
#  location_permissions: ^4.0.1
  pdfx: ^2.6.0
  rxdart: ^0.28.0
  #trust_fall:
  pushy_flutter: 2.0.22
#  image_picker_gallery_camera: ^0.3.0
  flutter_callkit_incoming: ^2.0.4+1
  # steps: ^0.0.1
  #flutter_phone_state:
  #  path: ./flutter_phone_state
  # flutter_phone_direct_caller:
  #   git:
  #     url: https://github.com/yanisalfian/flutter-phone-direct-caller.git
  vector_math: ^2.0.8



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
dependency_overrides:
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/regular.ttf
          style: normal
        - asset: fonts/semibold.ttf
        - asset: fonts/bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
