Map<String, dynamic> job1 = {
  "job_id": "12345",
  "job_alloc_id": "54321",
  "job_no": "JOB2024-001",
  "SchedDate": "2024-08-09",
  "SchedTime": "08:00 AM",
  "SiteContactCount": 2,
  "SiteContactName": "John Doe",
  "SiteContactMobile": "+1234567890",
  "Address": "123 Elm Street, Springfield",
  "job_desc": "Tree trimming and removal",
  "job_sp_desc": "Special instructions for trimming the oak tree",
  "wpcompanyid": "98765",
  "reqid": "REQ12345",
  "JobStatus": "Scheduled",
  "contractor_id": "67890",
  "updateAllowed": "true",
  "BeforeImagesExists": "true",
  "images": "https://example.com/images/before_image.jpg",
  "AfterImagesExists": "false",
  "deletebeforeimages": "false",
  "deleteAfterimages": "false",
  "deleteSiteHazardImages": "false",
  "deleteFenceImages": "false",
  "TreeInfoExists": "true",
  "costExists": "true",
  "SiteHazardFormExists": "false",
  "SiteHazardUploadExists": "true",
  "ScheduleExists": "true",
  "ImagesExists": "true",
  "JobReqId": "JREQ-2024-01",
  "JobDate": "2024-08-07",
  "Suburb": "Downtown",
  "Timeframe": "Morning",
  "InvoiceDate": "2024-08-08",
  "PayDate": "2024-08-15",
  "QuoteDate": "2024-08-01",
  "invoiceComplete": "false",
  "SiteHazard": "Yes",
  "FenceRequired": "No",
  "ScheduleDisplay": "08:00 AM - 12:00 PM",
  "AddressDisplay": "123 Elm Street, Springfield",
  "callDialogVersion": "1.0",
  "overdue": "false"
};

Map<String, dynamic> job2 = {
  "job_id": "67890",
  "job_alloc_id": "09876",
  "job_no": "JOB2024-002",
  "SchedDate": "2024-08-10",
  "SchedTime": "10:00 AM",
  "SiteContactCount": 1,
  "SiteContactName": "Jane Smith",
  "SiteContactMobile": "+0987654321",
  "Address": "456 Oak Avenue, Rivertown",
  "job_desc": "Fence installation",
  "job_sp_desc": "Install new wooden fence around the property",
  "wpcompanyid": "54321",
  "reqid": "REQ67890",
  "JobStatus": "Scheduled",
  "contractor_id": "12345",
  "updateAllowed": "false",
  "BeforeImagesExists": "false",
  "images": "https://example.com/images/fence_image.jpg",
  "AfterImagesExists": "true",
  "deletebeforeimages": "true",
  "deleteAfterimages": "true",
  "deleteSiteHazardImages": "false",
  "deleteFenceImages": "true",
  "TreeInfoExists": "false",
  "costExists": "true",
  "SiteHazardFormExists": "true",
  "SiteHazardUploadExists": "false",
  "ScheduleExists": "true",
  "ImagesExists": "true",
  "JobReqId": "JREQ-2024-02",
  "JobDate": "2024-08-08",
  "Suburb": "Rivertown",
  "Timeframe": "Afternoon",
  "InvoiceDate": "2024-08-09",
  "PayDate": "2024-08-16",
  "QuoteDate": "2024-08-02",
  "invoiceComplete": "true",
  "SiteHazard": "No",
  "FenceRequired": "Yes",
  "ScheduleDisplay": "10:00 AM - 02:00 PM",
  "AddressDisplay": "456 Oak Avenue, Rivertown",
  "callDialogVersion": "1.1",
  "overdue": "true"
};

Map<String, dynamic> job3 = {
  "job_id": "11223",
  "job_alloc_id": "33445",
  "job_no": "JOB2024-003",
  "SchedDate": "2024-08-11",
  "SchedTime": "01:00 PM",
  "SiteContactCount": 3,
  "SiteContactName": "Emily Johnson",
  "SiteContactMobile": "+1122334455",
  "Address": "789 Pine Street, Uptown",
  "job_desc": "Gutter cleaning",
  "job_sp_desc": "Clean and inspect gutters on the second floor",
  "wpcompanyid": "67890",
  "reqid": "REQ11223",
  "JobStatus": "Completed",
  "contractor_id": "98765",
  "updateAllowed": "true",
  "BeforeImagesExists": "true",
  "images": "https://example.com/images/gutter_image.jpg",
  "AfterImagesExists": "true",
  "deletebeforeimages": "true",
  "deleteAfterimages": "false",
  "deleteSiteHazardImages": "false",
  "deleteFenceImages": "false",
  "TreeInfoExists": "false",
  "costExists": "false",
  "SiteHazardFormExists": "true",
  "SiteHazardUploadExists": "true",
  "ScheduleExists": "true",
  "ImagesExists": "true",
  "JobReqId": "JREQ-2024-03",
  "JobDate": "2024-08-09",
  "Suburb": "Uptown",
  "Timeframe": "Early Afternoon",
  "InvoiceDate": "2024-08-10",
  "PayDate": "2024-08-17",
  "QuoteDate": "2024-08-03",
  "invoiceComplete": "false",
  "SiteHazard": "Yes",
  "FenceRequired": "No",
  "ScheduleDisplay": "01:00 PM - 03:00 PM",
  "AddressDisplay": "789 Pine Street, Uptown",
  "callDialogVersion": "1.2",
  "overdue": "false"
};

Map<String, dynamic> job4 = {
  "job_id": "44556",
  "job_alloc_id": "78901",
  "job_no": "JOB2024-004",
  "SchedDate": "2024-08-12",
  "SchedTime": "09:00 AM",
  "SiteContactCount": 1,
  "SiteContactName": "Michael Brown",
  "SiteContactMobile": "+2233445566",
  "Address": "101 Maple Road, Midtown",
  "job_desc": "Roof repair",
  "job_sp_desc": "Fix leaks on the roof and replace damaged shingles",
  "wpcompanyid": "23456",
  "reqid": "REQ44556",
  "JobStatus": "In Progress",
  "contractor_id": "54321",
  "updateAllowed": "true",
  "BeforeImagesExists": "true",
  "images": "https://example.com/images/roof_image.jpg",
  "AfterImagesExists": "false",
  "deletebeforeimages": "false",
  "deleteAfterimages": "false",
  "deleteSiteHazardImages": "false",
  "deleteFenceImages": "false",
  "TreeInfoExists": "false",
  "costExists": "true",
  "SiteHazardFormExists": "false",
  "SiteHazardUploadExists": "false",
  "ScheduleExists": "true",
  "ImagesExists": "true",
  "JobReqId": "JREQ-2024-04",
  "JobDate": "2024-08-09",
  "Suburb": "Midtown",
  "Timeframe": "Morning",
  "InvoiceDate": "2024-08-11",
  "PayDate": "2024-08-18",
  "QuoteDate": "2024-08-04",
  "invoiceComplete": "false",
  "SiteHazard": "No",
  "FenceRequired": "No",
  "ScheduleDisplay": "09:00 AM - 12:00 PM",
  "AddressDisplay": "101 Maple Road, Midtown",
  "callDialogVersion": "2",
  "overdue": "false"
};

Map<String, dynamic> job5 = {
  "job_id": "78901",
  "job_alloc_id": "12345",
  "job_no": "JOB2024-005",
  "SchedDate": "2024-08-13",
  "SchedTime": "03:00 PM",
  "SiteContactCount": 2,
  "SiteContactName": "Sarah Davis",
  "SiteContactMobile": "+5566778899",
  "Address": "202 Birch Lane, Oldtown",
  "job_desc": "Window replacement",
  "job_sp_desc": "Replace broken windows in the living room",
  "wpcompanyid": "34567",
  "reqid": "REQ78901",
  "JobStatus": "Scheduled",
  "contractor_id": "67890",
  "updateAllowed": "true",
  "BeforeImagesExists": "true",
  "images": "https://example.com/images/window_image.jpg",
  "AfterImagesExists": "true",
  "deletebeforeimages": "true",
  "deleteAfterimages": "true",
  "deleteSiteHazardImages": "true",
  "deleteFenceImages": "false",
  "TreeInfoExists": "false",
  "costExists": "true",
  "SiteHazardFormExists": "true",
  "SiteHazardUploadExists": "true",
  "ScheduleExists": "true",
  "ImagesExists": "true",
  "JobReqId": "JREQ-2024-05",
  "JobDate": "2024-08-10",
  "Suburb": "Oldtown",
  "Timeframe": "Late Afternoon",
  "InvoiceDate": "2024-08-12",
  "PayDate": "2024-08-19",
  "QuoteDate": "2024-08-05",
  "invoiceComplete": "false",
  "SiteHazard": "Yes",
  "FenceRequired": "No",
  "ScheduleDisplay": "03:00 PM - 05:00 PM",
  "AddressDisplay": "202 Birch Lane, Oldtown",
  "callDialogVersion": "1.4",
  "overdue": "false"
};
List<Map<String, dynamic>> mockJsonList = [job1, job2, job3, job4, job5];
